steps:
  # 1. Compilar a imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ta-na-hand:$COMMIT_SHA', '.']
  
  # 2. Enviar a imagem para o Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ta-na-hand:$COMMIT_SHA']
  
  # 3. Publicar no Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'ta-na-hand'
      - '--image'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ta-na-hand:$COMMIT_SHA'
      - '--region'
      - 'us-east1'
      - '--allow-unauthenticated'

images:
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/ta-na-hand:$COMMIT_SHA'
